AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Quarkus - quarkus-lambda-demo-1.0-SNAPSHOT

Parameters:
  ImageUri:
    Type: String

Resources:
  QuarkusLambdaDemo:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Ref ImageUri
      MemorySize: 256
      Timeout: 15
      Policies: AWSLambdaBasicExecutionRole